# ok this works.
# next step is to start tests in the image and get results!
name: CI
on: [workflow_dispatch]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/davidpratten/binder_trial:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Show what is there
        run: ls /home/jovyan/work
      - name: Run tests
        run: py.test /home/jovyan
