# ok this works.
# next step is to start tests in the image and get results!
name: CI
on: [workflow_dispatch]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/davidpratten/binder_trial:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      # The CD is required because when a container is run by Github the working directory is set by
      # GITHUB_WORKSPACE environment variable and defaults to /home/runner/work/my-repo-name/my-repo-name.
      # jovyan is the default non-root username chosen by Docker when building the image
      - name: Run tests
        run: cd /home/jovyan && py.test
